# 0. Configuration

In [1]:
# links to shared data MovieLens
# source on kaggle: https://www.kaggle.com/code/quangnhatbui/movie-recommender/data
RATINGS_SMALL_URL = 'https://drive.google.com/file/d/1BlZfCLLs5A13tbNSJZ1GPkHLWQOnPlE4/view?usp=share_link'
MOVIES_METADATA_URL = 'https://drive.google.com/file/d/19g6-apYbZb5D-wRj4L7aYKhxS-fDM4Fb/view?usp=share_link'

# 1. Modules and functions

In [2]:
# just to make it available to download w/o SSL verification
import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import numpy as np
import pandas as pd
import scipy.sparse as sp

from itertools import islice, cycle, product

from tqdm import tqdm_notebook
import warnings
warnings.filterwarnings('ignore')


## 1. 1. Helper functions to avoid copy paste

In [3]:
def read_csv_from_gdrive(url):
    """
    gets csv data from a given url (taken from file -> share -> copy link)
    :url: example https://drive.google.com/file/d/1BlZfCLLs5A13tbNSJZ1GPkHLWQOnPlE4/view?usp=share_link
    """
    file_id = url.split('/')[-2]
    file_path = 'https://drive.google.com/uc?export=download&id=' + file_id
    data = pd.read_csv(file_path)

    return data

# 2. Main

## 2.1. Load Data

`interactions` dataset shows list of movies that users watched, along with given ratings:

In [4]:
# interactions data
interactions = read_csv_from_gdrive(RATINGS_SMALL_URL)
interactions.head()

userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

`movies_metadata` dataset shows the list of movies existing on OKKO platform:

In [5]:
# information about films etc
movies_metadata = read_csv_from_gdrive(MOVIES_METADATA_URL)
movies_metadata.head(3)

adult                              belongs_to_collection    budget  \
0  False  {'id': 10194, 'name': 'Toy Story Collection', ...  30000000   
1  False                                                NaN  65000000   
2  False  {'id': 119050, 'name': 'Grumpy Old Men Collect...         0   

                                              genres  \
0  [{'id': 16, 'name': 'Animation'}, {'id': 35, '...   
1  [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...   
2  [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...   

                               homepage     id    imdb_id original_language  \
0  http://toystory.disney.com/toy-story    862  tt0114709                en   
1                                   NaN   8844  tt0113497                en   
2                                   NaN  15602  tt0113228                en   

     original_title                                           overview  ...  \
0         Toy Story  Led by Woody, Andy's toys live happily in his ...  ...   
1           Jumanji  When siblings Judy and Peter discover an encha...  ...   
2  Grumpier Old Men  A family wedding reignites the ancient feud be...  ...   

  release_date      revenue runtime  \
0   1995-10-30  373554033.0    81.0   
1   1995-12-15  262797249.0   104.0   
2   1995-12-22          0.0   101.0   

                                    spoken_languages    status  \
0           [{'iso_639_1': 'en', 'name': 'English'}]  Released   
1  [{'iso_639_1': 'en', 'name': 'English'}, {'iso...  Released   
2           [{'iso_639_1': 'en', 'name': 'English'}]  Released   

                                             tagline             title  video  \
0                                                NaN         Toy Story  False   
1          Roll the dice and unleash the excitement!           Jumanji  False   
2  Still Yelling. Still Fighting. Still Ready for...  Grumpier Old Men  False   

  vote_average vote_count  
0          7.7     5415.0  
1          6.9     2413.0  
2          6.5       92.0  

[3 rows x 24 columns]

In [6]:
movies_metadata['id'] = movies_metadata['id'].astype(str)
interactions['movieId'] = interactions['movieId'].astype(str)

In [7]:
# leave only those films that intersect with each other
interactions_filtered = interactions.loc[interactions['movieId'].isin(movies_metadata['id'])]
print(interactions.shape, interactions_filtered.shape)

(100004, 4) (44989, 4)


## 2.2 Data preparation using LightFM Dataset

To use implicit kNN method `fit` we need a sparse matrix in COOrdinate format. To achieve that we will use `scipy.sparse.coo_matrix` from scipy;


In [8]:
def get_coo_matrix(
        df: pd.DataFrame, 
        user_col: str,
        item_col: str, 
        users_mapping: dict, 
        movies_mapping: dict,
        weight_col: str = None
        ):
    if weight_col is None:
        weights = np.ones(len(df), dtype=np.float32)
    else:
        weights = df[weight_col].astype(np.float32)
    interaction_matrix = sp.coo_matrix((
        weights, 
        (
            df[user_col].map(users_mapping.get), 
            df[item_col].map(movies_mapping.get)
        )
    ))
    return interaction_matrix


In [9]:
# define users mapping
users_inv_mapping = dict(enumerate(interactions_filtered['userId'].unique()))
users_mapping = {v: k for k, v in users_inv_mapping.items()}
len(users_mapping)


671

In [10]:
# define movies mapping
movies_inv_mapping = dict(enumerate(interactions_filtered['movieId'].unique()))
movies_mapping = {v: k for k, v in movies_inv_mapping.items()}
len(movies_mapping)


2830

In [11]:
interactions_filtered

userId movieId  rating   timestamp
10          1    1371     2.5  1260759135
11          1    1405     1.0  1260759203
13          1    2105     4.0  1260759139
15          1    2193     2.0  1260759198
16          1    2294     2.0  1260759108
...       ...     ...     ...         ...
99983     671    4995     4.0  1064891537
99992     671    5816     4.0  1065111963
99993     671    5902     3.5  1064245507
99996     671    5991     4.5  1064245387
99997     671    5995     4.0  1066793014

[44989 rows x 4 columns]

In [12]:
# defining train set on the whole interactions dataset (as HW you will have to split into test and train for evaluation)
train_mat = get_coo_matrix(
    interactions_filtered,
    user_col = 'userId',
    item_col = 'movieId',
    users_mapping = users_mapping,
    movies_mapping = movies_mapping
    ).tocsr()


In [13]:
train_mat

<671x2830 sparse matrix of type '<class 'numpy.float32'>'
	with 44989 stored elements in Compressed Sparse Row format>

In [14]:
train_mat.todense()

matrix([[1., 1., 1., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [15]:
train_mat.todense().shape

(671, 2830)

## 2.3. Model Training & Evaluation

In [`implicit`](https://pypi.org/project/implicit/), there are various models and can be groupped into:
- Item-to-Item: KNN based on various similarities - CosineRecommender, BM25Recommender, TFIDFRecommender
- implicit ALS;
- Logistic Matrix Factorization;
- Bayesian Personalized Ranking (BPR)


### 2.3.1. Train Model

In [16]:
!pip install implicit

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.6/18.6 MB 7.0 MB/s eta 0:00:00


In [17]:
from implicit.nearest_neighbours import (
    CosineRecommender,
    BM25Recommender,
    TFIDFRecommender
    )


Note that in item-to-item models we need to provide matrix in the form of item-user by transposing initial COO matrix user-item


In [18]:
# fit the model
cosine_model = CosineRecommender(K = 20)
cosine_model.fit(train_mat.T)


  0%|          | 0/671 [00:00<?, ?it/s]

### 2.3.2. Evaluate the Model

In [19]:
# let's make sense-check
top_N = 10
user_id = interactions_filtered['userId'].iloc[0]
row_id = users_mapping[user_id]
print(f'Rekko for user {user_id}, row number in matrix - {row_id}')

Rekko for user 1, row number in matrix - 0


In [20]:
# create mapper for movieId and title names
movie_name_mapper = dict(zip(movies_metadata['id'], movies_metadata['original_title']))

In [21]:
recs = cosine_model.recommend(
    row_id,
    train_mat,
    N = top_N,
    filter_already_liked_items = True
    )
print(recs)
recs = pd.DataFrame(recs).T.rename(columns = {0: 'col_id', 1: 'similarity'})
recs['inv_movie_id'] = recs['col_id'].astype(int)
recs['movieId'] = recs['inv_movie_id'].map(movies_inv_mapping.get)
recs['title'] = recs['movieId'].map(movie_name_mapper)
recs


(array([653, 129, 606, 294, 337, 648, 579, 399, 278, 150], dtype=int32), array([0.861587  , 0.84453135, 0.65406408, 0.62514078, 0.59385569,
       0.57749882, 0.57168118, 0.56144224, 0.56144224, 0.55708601]))


col_id  similarity  inv_movie_id movieId                         title
0   653.0    0.861587           653   74458        Mere Brother Ki Dulhan
1   129.0    0.844531           129    1994       The Most Dangerous Game
2   606.0    0.654064           606    8011  Highlander III: The Sorcerer
3   294.0    0.625141           294      70           Million Dollar Baby
4   337.0    0.593856           337     170                 28 Days Later
5   648.0    0.577499           648   68954                     Longitude
6   579.0    0.571681           579    5956                        Joshua
7   399.0    0.561442           399    1088                   Whale Rider
8   278.0    0.561442           278    1584                School of Rock
9   150.0    0.557086           150    2100               The Last Castle

# TODO
- Make global train/ global test split -- train the model appropiately and predict on test set;
- Wrap up in function recommendations - lfm_recommend();
- Calculate `NDCG@10` on test set

In [22]:
from datetime import datetime
interactions_filtered = interactions_filtered.sort_values(by='timestamp', ascending=True)
#hot_users = [i  for i in set(interactions_filtered['userId']) if list(interactions_filtered['userId']).count(i)>3]
#df = interactions_filtered[interactions_filtered['userId'] in hot_users]
#max_date = max(interactions_filtered['date'])
#train = interactions_filtered[(interactions_filtered['date'] < max_date - pd.Timedelta(days=7))]
#test = interactions_filtered[(interactions_filtered['date'] >= max_date - pd.Timedelta(days=7))]

split_point = int(0.75 * len(interactions_filtered))

train = interactions_filtered[:split_point]
test = interactions_filtered[split_point:]

In [23]:
global_train_mat = get_coo_matrix(
    train,
    user_col = 'userId',
    item_col = 'movieId',
    users_mapping = users_mapping,
    movies_mapping = movies_mapping
    ).tocsr()

global_test_mat = get_coo_matrix(
    test,
    user_col = 'userId',
    item_col = 'movieId',
    users_mapping = users_mapping,
    movies_mapping = movies_mapping
    ).tocsr()

In [24]:
cosine_model = CosineRecommender(K = 20)
cosine_model.fit(global_train_mat.T)


  0%|          | 0/671 [00:00<?, ?it/s]

In [25]:
top_N = 10
user_id = train['userId'].iloc[0]
row_id = users_mapping[user_id]

In [26]:
recs2 = cosine_model.recommend(
    userid=row_id,
    user_items=global_test_mat,
    N = top_N,
    filter_already_liked_items = True
    )

recs2

(array([653, 129, 579, 460, 606, 337, 648, 399, 278, 150], dtype=int32),
 array([0.861587  , 0.84453135, 0.81676949, 0.77607861, 0.65406408,
        0.59385569, 0.57749882, 0.56144224, 0.56144224, 0.55708601]))

In [28]:
def lfm_recommend(file, row_id,test,N=10, filter_already_liked_items=True):
    global cosine_model
    recs = cosine_model.recommend(
        userid=row_id,
        user_items=test,
        N = top_N,
        filter_already_liked_items = filter_already_liked_items
        )
    recs = pd.DataFrame(recs).T.rename(columns = {0: 'col_id', 1: 'similarity'})
    recs['inv_movie_id'] = recs['col_id'].astype(int)
    recs['movieId'] = recs['inv_movie_id'].map(movies_inv_mapping.get)
    recs['title'] = recs['movieId'].map(movie_name_mapper)
    return recs

In [29]:
recs

col_id  similarity  inv_movie_id movieId                         title
0   653.0    0.861587           653   74458        Mere Brother Ki Dulhan
1   129.0    0.844531           129    1994       The Most Dangerous Game
2   606.0    0.654064           606    8011  Highlander III: The Sorcerer
3   294.0    0.625141           294      70           Million Dollar Baby
4   337.0    0.593856           337     170                 28 Days Later
5   648.0    0.577499           648   68954                     Longitude
6   579.0    0.571681           579    5956                        Joshua
7   399.0    0.561442           399    1088                   Whale Rider
8   278.0    0.561442           278    1584                School of Rock
9   150.0    0.557086           150    2100               The Last Castle

In [30]:
from implicit.evaluation import ndcg_at_k
ndcg_at_k(cosine_model, global_train_mat.T, global_test_mat.T, K = 10)

  0%|          | 0/1775 [00:00<?, ?it/s]

0.022810172879520675